inherit_from: service_module/.rubocop.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Style/RaiseArgs:
  EnforcedStyle: compact
Metrics/ModuleLength:
  Max: 300
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'lib/argu/test_mocks.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
RSpec/ExampleLength:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
