inherit_from: service_module/.rubocop.yml
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'doc/**/*'
    - 'app/assets/javascripts/_*'
    - 'app/assets/javascripts/_*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
RSpec/ExampleLength:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/RepeatedExample:
  Enabled: false
