build:
  version: 2016-03-14
  steps:
    service:
      name: _env(IMAGE_NAME)
      dockerfile: Dockerfile
      secrets:
        id_rsa:
          type: file
          value: _env(HOME)/.ssh/deploy_key

