development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['TOKEN_SERVICE_DATABASE'] %>
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
  schema_search_path: 'public,shared_extensions'
test:
  <<: *default
  database: token_service_test
production: &production
  <<: *default
staging:
  <<: *production
