development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['TOKEN_SERVICE_DATABASE'] %>
  pool: 5
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
test:
  adapter: sqlite3
  encoding: unicode
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
production: &production
  <<: *default
staging:
  <<: *production
