development: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  jwt_encryption_token: <%= ENV['JWT_ENCRYPTION_TOKEN'] %>
test:
  <<: *default
production:
  <<: *default
staging:
  <<: *default
